- .gitignore
Cf [Twitter](https://twitter.com/Palleas/status/629366402227531777) 😬
> Stop ignoring Podfile.lock

- Makefile
!!!!!!¡¡¡¡¡¡¡ PULL REQUEST #1 ¡¡¡¡¡¡¡¡!!!!!!
¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡
> @orta=> Changed 'setup' to 'artsy' in Makefile

- fastlane/Fastfile
This will also switch from `http` to `https` :+1:
> Raise an exception if something goes wrong

- README.md
Some people at C4Q were having difficulties with running the oss commands.
> @sarah => Add a troubleshooting section to the README

- Podfile.lock
> @sarah => Adds back the podfile lock

- Podfile.lock
Looks like the last one was broken.
> @sarah => Make Podfile resolve for Tests

- Classes/Categories/Categories.h
- Makefile
- README.md
When I started going through installation with some students at Coalition for Queens, I found a few blockers, documented in #6 - this fixes #6
> @sarah => Improve the validations on the makefile

- ArtsyFolio Tests/Views/ARArtworkInfoAdditionalMetadataViewTests.m
- Classes/Artwork/Artwork  Detail View/Info Views/ARArtworkInfoAdditionalMetadataView.m
- Podfile
- Podfile.lock
> @orta=>Fixed inventory id bug

- .slather.yml
- .travis.yml
- Gemfile
- Gemfile.lock
- README.md
- docs/CHANGELOG.yml
Adds a new thing to the README too.
> @sarah => Updates CHANGELOG & brings back code coverage

- Classes/Controllers/Settings/ARSettingsViewController.m
All should work as expected now :horse_racing:
> @orta=>Bug fix for sync button

- Artsy Folio.xcodeproj/project.pbxproj
- Classes/Controllers/Settings/ARLabSettings.storyboard
- Classes/Controllers/Settings/ARLabSettingsMasterViewController.h
- Classes/Controllers/Settings/ARLabSettingsMasterViewController.m
- Classes/Controllers/Settings/ARLabSettingsNavController.h
- Classes/Controllers/Settings/ARLabSettingsNavController.m
- Classes/Controllers/Settings/ARLabSettingsViewController.h
- Classes/Controllers/Settings/ARLabSettingsViewController.m
- Classes/Controllers/Top View Controller/ARTopViewController.m
- Classes/Util/App/AROptions.h
- Classes/Util/App/AROptions.m
> @orta=>admin option + complete ib work for master view

- Supporting Files/Info.plist
Allows HTTP connections for iOS 9 devices
> @orta=>Transport security issue

- Classes/Controllers/Settings/ARAdminSettingsViewController.m
- Classes/Views/Custom Controls/Switch Views/ARToggleSwitch.h
- Classes/Views/Custom Controls/Switch Views/ARToggleSwitch.m
> @orta=>made ARToggleSwitch friendlier

- Artsy Folio.xcodeproj/project.pbxproj
- Podfile
- Supporting Files/ArtsyFolio Tests-Info.plist
- Supporting Files/Info.plist
- docs/CHANGELOG.yml
> @orta=> Fixes for iOS 9

- ArtsyFolio Tests/Models/ArtworkModelTests.m
- Classes/Constants/ARFeedKeys.h
- Classes/Constants/ARFeedKeys.m
- Classes/Models/Artwork.m
- docs/CHANGELOG.yml
> @orta=> unit conversion

- Classes/Controllers/Settings/ARLabSettingsMasterViewController.m
- docs/CHANGELOG.yml
I present... the most complicated PR ever conceived.
To be merged after the other settings.
> [WIP]intercom support

- Artsy Folio.xcodeproj/project.pbxproj
- ArtsyFolio Tests/Util/ARStubbedNetworkQualityIndicator.h
- ArtsyFolio Tests/Util/ARStubbedNetworkQualityIndicator.m
- ArtsyFolio Tests/View Controllers/ARLabSettingsSyncViewControllerTests.m
- ArtsyFolio Tests/View Controllers/ARStubbedLoginNetworkModel.m
- Classes/Controllers/Login & Setup/Login/ARLoginNetworkModel.h
- Classes/Controllers/Login & Setup/Login/ARLoginNetworkModel.m
- Classes/Controllers/Login & Setup/Login/ARLoginViewController.m
- Classes/Controllers/Settings/ARLabSettings.storyboard
- Classes/Controllers/Settings/ARLabSettingsSyncViewController.h
- Classes/Controllers/Settings/ARLabSettingsSyncViewController.m
- Classes/Util/App/ARNetworkQualityIndicator.h
- Classes/Util/App/ARNetworkQualityIndicator.m
Creates a network object that determines the network connectivity when connecting to apple + artsy. Offers a block API for getting an approximation for how good the network is where you are currently.
> Initial work on a network quality observer

- ArtsyFolio Tests/View Controllers/ARLabSettingsMasterViewControllerTests.m
- ArtsyFolio Tests/View Controllers/ARLabSettingsPresentationModeViewControllerTests.m
- Classes/Controllers/Settings/ARLabSettingsMasterViewController.m
- Classes/Controllers/Settings/ARLabSettingsPresentationModeViewController.m
> @orta=> Post artworkReloadNotification when Presentation Mode is toggled

- .travis.yml
- Dangerfile
- Gemfile
- Gemfile.lock
- docs/CHANGELOG.yml
Initial work on a Dangerfile.
re: https://github.com/artsy/mobile/issues/31
> @sarahscott => Adds a dangerfile

- Gemfile
- Gemfile.lock
- circle.yml
- docs/CHANGELOG.yml
- fastlane/Fastfile
> Validate keys on a beta deploy + update danger

- Classes/ARAppDelegate.m
- Classes/ARInitialViewControllerSetupCoordinator.h
- Classes/ARInitialViewControllerSetupCoordinator.m
- Makefile
- docs/CHANGELOG.yml
This is a quick fix for locking out ineligible partners if they refuse to sync again, but I'm making a separate issue to make lockout more robust in general and easier to use as an API.
Fixes #146
> @orta => Updated lockout

- Artsy Folio.xcodeproj/project.pbxproj
- ArtsyFolio Tests/Sync/ARStubbedDRBOperation.h
- ArtsyFolio Tests/Sync/ARStubbedDRBOperation.m
- ArtsyFolio Tests/Sync/ARStubbedSyncDelegate.h
- ArtsyFolio Tests/Sync/ARStubbedSyncDelegate.m
- ArtsyFolio Tests/Sync/ARStubbedSyncProvider.h
- ArtsyFolio Tests/Sync/ARStubbedSyncProvider.m
- ArtsyFolio Tests/Sync/ARSync+TestsExtension.m
- ArtsyFolio Tests/Sync/SyncSpec.m
- Classes/Sync/ARSync.m
- docs/CHANGELOG.yml
Curious about your opinion on this - I'm not quite sure how to test it right now but it works!
Fixes #125
> @orta=> Fix for settings button showing sync icon on iPad

- Gemfile
- Gemfile.lock
- Makefile
- fastlane/Fastfile
Danger will complain about the changelog, we can live with that as the red.
> Ensure betas work with Hockey

- Makefile
> @orta=>Fixes mogenerator bug with this one weird trick

- Makefile
- README.md
- docs/CHANGELOG.yml
As the title says.
Readme contains some info I found useful getting setup. 
@sarahscott @orta
> Removed the match/certs step in the makefile + a readme update

- ArtsyFolio Tests/Testing Util Objects/AROHHTTPNoStubAssertionBot.m
- Dangerfile
- Makefile
Basically the same as in [eigen](https://github.com/artsy/eigen/pull/1140) 
@orta I assume this is what you meant?
> @orta => Added a git ingore to makefile for appdelegate+devtools file #trivial

- docs/Folio.paw
- docs/README.md
- docs/getting_started.md
- docs/overview.md
Will go along with http://artsy.github.io/blog/2016/04/14/net-working-with-paw/
> Add the Paw file, and updates docs with links to blog posts #trivial

- README.md
Preview: https://github.com/artsy/energy/tree/orta-readme_16#readme
Updates with the meta from https://github.com/artsy/eigen/pull/1484
> Improve the readme for 2016

- fastlane/Fastfile
Brings us inline with Eigen's deployment structure, mostly.
> Deployment changes

- Dangerfile
- Gemfile
- Gemfile.lock
> Update Danger #trivial

- Classes/Spotlight/ARSpotlightExporter.m
- dependencyci.yml
- docs/CHANGELOG.yml
- fastlane/Fastfile
Another crash fix from an audit this morning, and some changes re: deployment.
> @Orta => artist crash

- .gitignore
- Gemfile
- Gemfile.lock
- docs/CHANGELOG.yml
Want to verify https://github.com/danger/danger/pull/654 on a real project
> Update to latest Danger

- ArtsyFolio Tests/Util/ARDefaultsTests.m
- Classes/Artwork/Artwork  Detail View/Info Views/ARArtworkInfoAdditionalMetadataView.m
- Classes/Constants/ARDefaults.m
- Classes/Controllers/Login & Setup/Login/ARLoginViewController.m
- docs/CHANGELOG.yml
And use smart quotes in the default email subject.
The ArtsyAuthentication library, and my helper functions around disconnects make no thread guarantees, so ensure UI work happens on thread 0.
> Ensure that login UI changes are on the main thread

- Classes/Artwork/Artwork  Detail View/ARModernArtworkInfoViewController.m
- Classes/Operations/AFHTTPRequestOperation+ARFileDownload.m
- Classes/Sync/Documents/ARDocumentFileDownloader.m
- Classes/Sync/Images/ARImageDownloader.m
- Gemfile
- Gemfile.lock
Fixes #253 - which is our biggest crasher ATM
> Crash fixes related to failed sync downloads

- Artsy Folio.xcodeproj/project.pbxproj
- ArtsyFolio Tests/Models/ImageModelTests.m
- Classes/Artwork/Artwork  Detail View/ARModernArtworkInfoViewController.m
- Classes/Models/Image.m
- Classes/Operations/AFHTTPRequestOperation+ARFileDownload.m
- Classes/Sync/Documents/ARDocumentFileDownloader.m
- Classes/Sync/Images/ARImageDownloader.m
- Gemfile
- Gemfile.lock
This fixes an issue brough up i slack, but not in the issues - [see here](https://artsy.slack.com/archives/partner-s-help/p1484073907001165)
Relies on #257 
For an example Artwork, see https://api.artsy.net/api/v1/artwork/eric-fischl-dancers-suite-blue-couple
> Show images in the grid when gravity does not provide an aspectRatio

- ArtsyFolio Tests/Util/AREmailComposerTests.m
- Classes/Util/App/ARFeedTranslator.h
- Classes/Util/App/AROptions.h
- Classes/Util/App/CoreDataManager.h
- Classes/Util/Emails/AREmailComposer.h
- Classes/Util/Emails/AREmailComposer.m
- Classes/Util/Emails/AREmailSettings.h
- Classes/Util/Migrations/ARMigrationController.h
- docs/CHANGELOG.yml
Ensures that because we don't retain the selection ordering, there is at least some sense of determinism in the order for the artworks Folio emails.
also, a lot of doc updates
> Add deterministic email sorting on an artwork

- Classes/Models/Document.m
- Classes/Util/Emails/AREmailComposer.m
- docs/CHANGELOG.yml
Fixes: https://artsyproduct.atlassian.net/browse/BUGS-680
> Fix a crash with attaching documents

- Artsy Folio.xcodeproj/project.pbxproj
- Classes/ARAppDelegate.m
- Classes/Util/App/ARAuthValidator.h
- Classes/Util/App/ARAuthValidator.m
- Classes/Util/App/ARUserManager.h
- Classes/Util/App/ARUserManager.m
- docs/CHANGELOG.yml
Because I changed my password, I couldn't do things like sync or change availability. Now I find out why. Mostly just a port of the code I wrote for Eigen.
> Handle re-authing when you lose session, and/or change password

- Classes/Controllers/Collections Controllers/Containers/ARArtworkContainerViewController.m
- docs/feature_map.md
And improve the feature map
#trivial
> Add support for making the remove artwork via long press sync via the Album sync

- Podfile.lock
- docs/CHANGELOG.yml
Mainly to get https://github.com/artsy/Artsy-Authentication/pull/21 in
Testing by logging in locally.
/cc @joeyAghion
> Use latest build of Artsy Auth

- Classes/Sync/ARSync.h
- Classes/Sync/ARSync.m
- Classes/Util/App/ARLogoutManager.m
- Makefile
This should be easier than requiring partners to manually sync.
> [MX-288] Persist albums when logging out

- Classes/Controllers/Settings/ARSettingsMenuViewController.m
- Classes/Sync/ARSync.h
- Classes/Sync/ARSync.m
- Classes/Util/App/ARLogoutManager.m
- Makefile
- docs/CHANGELOG.yml
These changes have already been submitted; this PR is to get the release reflected properly Horizon, our release tracker.
> Updates beta branch
