Classes/Controllers/Settings/ARSettingsViewController.m
Podfile.lock

This would in theory be replicated with this test:
``` objc
it(@"keeps track of its sync view", ^{
ARSettingsViewController *settingsVC = [[ARSettingsViewController alloc] init];
UINavigationController *nav = [[UINavigationController alloc] initWithRootViewController:settingsVC];
UIWindow *window = [[UIWindow alloc] initWithFrame:CGRectMake(0, 0, 320, 320)];
window.rootViewController = nav;
[window makeKeyAndVisible];
UIViewController *newVC = [[UIViewController alloc] init];
[nav pushViewController:newVC animated:NO];
expect(^{
[settingsVC beginAppearanceTransition:YES animated:NO];
}).toNot.raise(nil);
});
```
But I couldn't find a way to make it raise correctly in tests, so alas, opted to not include it.

@sarah => Fix for crash with going to the email view controller in settings and back

---

Artsy Folio.xcodeproj/project.pbxproj
ArtsyFolio Tests/Models/PartnerModelTests.m
ArtsyFolio Tests/View Controllers/ARZeroStateMessageViewControllerTests.m
Classes/ARInitialViewControllerSetupCoordinator.m
Classes/Categories/ARBaseViewController+TransparentModals.h
Classes/Controllers/Login & Setup/ARFolioMessageViewController.xib
Classes/Controllers/Login & Setup/ARZeroStateMessageViewController.h
Classes/Controllers/Login & Setup/ARZeroStateMessageViewController.m
Classes/Models/Partner.m

fixes #12 
Previously we would use a Partner's `artworks_count` data from the server to detect if we need to show a zero-state screen. Problem is, that is only updated once a day. So if you go from 0 -> X, then Folio didn't know.
So this PR adds the ability to run a re-sync from the zero-state screen, and will also query the internal Artworks database to see if we have some artworks.

@jory => Adds support for checking the amount of Artworks in the db

---

Classes/Categories/ARBaseViewController+TransparentModals.h
Classes/Categories/ARBaseViewController+TransparentModals.m

I wanted to use this category for the settings panel but with cross-dissolve instead of the bouncy spring effect. 
You can now choose between the two or use the legacy method for the original springy one. I've verified that it works with the storyboard in my other PR.

@orta=>Revamped transparent modal animations

---

Classes/Models/ArtistDocument.m
Classes/Models/Document.h
Classes/Models/Document.m
Classes/Models/ShowDocument.m
Classes/Operations/ARPDFThumbnailCreationOperation.m
Classes/Operations/ARThumbnailCreationOperation.m
Classes/Sync/Documents/ARDocumentThumbnailCreator.m

The document thumbnail creator was checking for fileExists before it should have been, so it wasn't able to properly store thumbnails where they were supposed to be. I'm thinking it would make sense to have a method that creates a new thumbnail filepath and a different method for accessing an existing filepath (which should also return the generic one if the thumbnail doesn't exist).
Thoughts?

[WIP] @orta=> Document thumbnail issue

---

Artsy Folio.xcodeproj/project.pbxproj
ArtsyFolio Tests/ARStubbedAnalytics.h
ArtsyFolio Tests/ARStubbedAnalytics.m
ArtsyFolio Tests/Sync/ARSyncAnalyticsSpec.m
Classes/Sync/ARSync.h
Classes/Sync/ARSync.m
Classes/Sync/ARSyncPlugins.h
Classes/Sync/SyncPlugin/ARSyncAnalytics.h
Classes/Sync/SyncPlugin/ARSyncAnalytics.m
Podfile

We have a lot of side effects in the ARSync. This is a way to formalise how we do before and after hooks on a sync, a lot of things could do this. The metadata deletion, the spotlight integration and saving etc. I don't think I'll be getting around to it soon, but I have another idea I want to formalise before I go on to those.
This pattern makes it _way_ easier to test the behaviour! In honour of this, I have created an easy way to test whether the code you're testing is making analytics calls. 
Note: We have migrated to the _new_ CocoaPods format for the Podfile, where you cannot use global scope. This should speed up compiles slightly, but more importantly means there's only one instance of each class in the app. ARAnalytics was getting quite confused. I would strongly recommend …

@sarahscott => Create ARSyncPlugin infrastructure

---

Makefile
Podfile
docs/CHANGELOG.yml

You'll need to set this, as I'm going to make all Artsy projects do it this way. Removes Google Chrome from `make pr` - I had stopped using GitHub GIFs.

@sarahscott => Use new env var to indicate you're artsy staff

---

ArtsyFolio Tests/View Controllers/ARLoginViewControllerTests.m
ArtsyFolio Tests/View Controllers/ARStubbedLoginNetworkModel.h
ArtsyFolio Tests/View Controllers/ARStubbedLoginNetworkModel.m
Classes/ARAppDelegate.m
Classes/Constants/ARNetworkConstants.h
Classes/Constants/ARNetworkConstants.m
Classes/Constants/ARNotifications.h
Classes/Constants/ARNotifications.m
Classes/Controllers/Login & Setup/Login/ARLoginNetworkModel.h
Classes/Controllers/Login & Setup/Login/ARLoginNetworkModel.m
Classes/Controllers/Login & Setup/Login/ARLoginViewController.h
Classes/Controllers/Login & Setup/Login/ARLoginViewController.m
Classes/Util/App/ARRouter.h
Classes/Util/App/ARRouter.m
Classes/Util/App/ARUserManager.h
Classes/Util/App/ARUserManager.m
Podfile
Podfile.lock
docs/CHANGELOG.yml

* I've moved our authentication networking to work via [Artsy_Authentication](https://github.com/artsy/Artsy-Authentication). Which makes 3/4 apps now.
* I've de-singleton'd the ARUserManager
* I've improved our error messaging. The flow is different now.
-  We try log them in, if it succeeds, continue.
-  Otherwise, try ping a known artsy route for checking if artsy is up
- if that passes then the error message is likely legit.
- if that fails, check if apple.com is up.
- if that passes then Artsy is down
- if that fails then the user is offline
Previously if there were any network issues, then it is assumed that Artsy is down, which was pretty true when I wrote the app login 4 years ago, but not true anymore.

@sarahscott => Move to artsy authentication, and improve login error messages

---

ArtsyFolio Tests/Models/ArtworkModelTests.m
Classes/Models/Artwork.m

This would crash for KOW and I'm sure other international galleries that use the metric field, so I made it a bit smarter.

@orta=>Quick fix for decimal overflow

---

Makefile

@sarahscott @orta 
`make oss` wasn't working, as there was no rule to make the ci_keys target. Took it out, seemed to all work fine? It now preps, pod installs, and you get your workspace just fine :). 
To get it to build, there's still a thing with fonts, but that will be PR 2 from me ^_^. 
Also - do I PR this onto master? Are there any rules around this?

Took out ci_keys as there is no rule to make that target

---

ArtsyFolio Tests/Testing Util Objects/AROHHTTPNoStubAssertionBot.m

Namely, `XCFail` over `_XCTPrimitiveFail`.

Use public XCTest macro instead of "private" one

---

ArtsyFolio Tests/Util/AREmailComposerTests.m
Classes/Categories/UIDevice+Testing.m
Classes/Models/Partner.h
Classes/Models/Partner.m
Classes/Util/App/CoreDataManager.m
Classes/Util/Emails/AREmailComposer.m
Resources/email_artwork_template.html
docs/CHANGELOG.yml

https://github.com/artsy/energy/issues/181 
Now at the end of the artwork section of an email, there is a "Open on Artsy." - with "Artsy" being clickable and will take you directly to the artwork.

Add support for linking to Artsy on a public Artwork

---

Classes/Controllers/Collections Controllers/Hosts/ARHostSelectionController.m

Fixes #180
This bug is new to iOS9, what I think changed is that `sizeToFit` on a button now does not perform a layout pass, meaning AL won't override the size to be the one you have constrained, but instead will set the size of the view to the `sizeToFit` size. 
I expect the size to fit was needed in older versions, but runs fine in iOS8 👍

Remove the size to fit on select buttons for selections on iPhone

---

Classes/Constants/ARNetworkConstants.m
Classes/Controllers/Settings/ARSyncSettingsViewController.m
docs/CHANGELOG.yml

Fixes #198
We were over retaining the networking and so it wasn't being disconnected when you let the sync screen. Resulting in more traffic than expected,
/cc @joeyAghion - sorry it took so long to get around to https://github.com/artsy/energy/pull/116#issuecomment-215579062

Convert to using a less resource intense API route for network quality 

---

Classes/Util/Debugging/ARAnalyticsHelper.m
docs/CHANGELOG.yml

Fixes #202 
I *think* this was so that it was easier to track an individual event to either a partner or a user throughout the analytics pipeline. #trivial

Per-Event Analytics Improvements

---

Classes/Artwork/View In Room/ARPadViewInRoomViewController.m
Classes/Categories/UIDevice+deviceInfo.h
Classes/Categories/UIDevice+deviceInfo.m
docs/CHANGELOG.yml

This is not a _perfect_ answer, as effectively is zooms in a bit to ensure everything fits, but it is using retina images, so it feels fine on an iPad.

Add a hot-fix for VIR iPad Pro sizes - fixes #102 #200

---

README.md
docs/getting_started.md

With af3d259 I moved the staff stuff together, but upon further investigation, this was wrong. If you don't set that flag prior to installing pods you'll get the wrong fonts and be confused. This happened to me and I fixed it by accident. Later, I was reading the Podfile and figured out what happened.
This commit calls attention to the flag being set before the pods are installed.

Call out staff flag earlier

---

README.md

I noticed that our copyright line was inconsistent across projects and
often still listed 2016. So, I worked with Yayoi to figure out what the
right language was and am now copy/pasting to achieve consistency.

Update License section

---

LICENSE
README.md

Ok, last PR on license/copyright stuff today, promise! Turns out the copyright line belongs in the LICENSE file and that should be the single source of truth for this info. While I was at it, I updated the copy slightly to match the default copy from the GitHub template.

Update LICENSE file

---

Classes/Artwork/Paging/ARArtworkSetViewController.m
Classes/Controllers/Collections Controllers/Hosts/ARHostViewController.m
Classes/Theming/ARTheme.h
Classes/Theming/ARTheme.m
Classes/Util/Emails/AREmailComposer.m
docs/CHANGELOG.yml

In #271 @starsirius found that the mail compose view would "lose" the value of the to field on blur. Turns out that this was a side-effect of setting the tint color on Window. This PR addresses the bug by forcing the tint color to be black prior to presenting the mail composer view and then switching it back to whatever it was on dismissal of that view.
Technically speaking all that's required here is 3253c2a, but it felt weird to not extract some helper methods, so that's what I did with 64ac201 and fb37924. Interested in feedback on this!

Fix email tint bug

---

ArtsyFolio Tests/Models/DocumentModelTests.m
Classes/Contexts/Finding and Searching/NSFetchRequest+ARModels.m
Classes/Controllers/Collections Controllers/Hosts/ARShowViewController.m
Classes/Data Sources/ARBrowseProvider.h
Classes/Data Sources/ARBrowseProvider.m
Classes/Models/Artist.m
Classes/Spotlight/ARSpotlightExporter.m
Classes/Sync/ARSyncDeleter.m
Classes/Util/Debugging/ARLogging.m
Classes/Views/Grid View & Items/ARGridView.h
Externals/RESTKit/NSManagedObject+ActiveRecord.m

Working through the second day of [CQC](https://www.codequalitychallenge.com/) and went through and audited the todos. Some of them I opened issues for and others I just ignored - hope that's ok!

Nuke todos

---

Classes/ARAppDelegate.m
Classes/Sync/Partner & User Metadata/ARPartnerFullMetadataDownloader.m
Classes/Util/App/ARUserManager.h
Classes/Util/App/ARUserManager.m
docs/CHANGELOG.yml

I honestly have no idea how it could happen, but it must, somehow.
This crash is when either a username, or a password is not set, so it will now send the user to a login screen instead of letting them through into the app.

Adds a crash fix for when you *somehow* have no stored username/password

---

Classes/Controllers/Settings/ARSyncSettingsViewController.m
Classes/Controllers/Settings/ARSyncSettingsViewModel.h
Classes/Controllers/Settings/ARSyncSettingsViewModel.m
Podfile
Podfile.lock
docs/CHANGELOG.yml

I think an OS update, or tooling update broke the KVO controller we were using to separate the View Model from the View inside the settings page. There were no more updates to the lib, so I removed the dependency and switched to good old delegation.

Bring back the settings sync progress

---

Classes/Contexts/Red Dot/ARPresentAvailabilityChoiceViewController.m
Classes/Models/Artwork.h
docs/CHANGELOG.yml
docs/THANKS.md

In volt the options you can see for an artwork's availability is different depending. on the type of Partner you are. This makes Folio match them.

Match the options for availabilities to CMS'

---

Classes/Sync/ARSync.m
Classes/Util/App/ARFileUtils.m
docs/CHANGELOG.yml

This PR adds basic album recovery. Here's how it works:
- On every sync, we persist all the albums to a flat file that is kept outside the normal database. It maps album names to a list of artwork IDs.
- When the app is first launched, after the first sync is completed and we can rely on the local database having all the artworks, we re-create the albums based on the persisted data.
Things that worry me and I want to look into a bit more:
Once merged:
Albums still won't sync between devices, but this should still improve the situation for partners when, for example, they get logged out due to changing their password.

Basic album persisting
